steps:
  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest',
      '.'
    ]

  # Artifact Registryへのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'
    ]

# ビルドオプション
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# 置換変数のデフォルト値
substitutions:
  _REGION: 'asia-northeast1'
  _REPOSITORY: 'cloud-workstations'
  _IMAGE_NAME: 'custom-workstation'
  _TAG: '${BUILD_ID}'

# タイムアウト設定
timeout: '1200s'
